doc api v1 game and public - initial version
redcraft-org/redcraft_website_back pull request #19
Opened 2021-08-30 20:17 UTC by Likyaz

2021-08-30 20:24 UTC, Omeganx approved these changes

2021-08-30 20:31 UTC, Likyaz commented on doc/api-v1-game.apib
> +    + uuidf: `minecraft:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX` (string, required) - Regex: `(discord|minecraft|player):(\S*)`
```suggestion
    + uuid: `minecraft:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX` (string, required) - Regex: `(discord|minecraft|player):(\S*)`
```

2021-08-30 22:32 UTC, lululombard requested changes
Some typos and tabs, also please include support for currencies, and change creations to HTTP 201

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +    + language: fr (string, required) - Language of the article.
```suggestion
    + language: fr (string, required) - language of the article
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +    + language: `fr` (string, required) - Language of the article.
```suggestion
    + language: `fr` (string, required) - Language of the article
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ per_page: 5 (number, optional) - number of donations per page
```suggestion
	+ per_page: 5 (number, optional) - Number of donations per page
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +    + page: 3 (number, optional) - current page
```suggestion
    + page: 3 (number, optional) - Current page
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ donation_count: 1 (bool, optional) -  return `donation count`
```suggestion
	+ donation_count: 1 (bool, optional) -  Return `donation count`
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ refunded_count: 1 (bool, optional) - return `refunded count`
```suggestion
	+ refunded_count: 1 (bool, optional) - Return `refunded count`
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ donation_amount: 1 (bool, optional) - return `donation amount`
```suggestion
	+ donation_amount: 1 (bool, optional) - Return `donation amount`
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ refunded_amount: 1 (bool, optional) - return `refunded amount`
```suggestion
	+ refunded_amount: 1 (bool, optional) - Return `refunded amount`
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ donation_count: 1 (bool, optional) -  return `donation count`
```suggestion
	+ donation_count: 1 (bool, optional) -  Return `donation count`
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ refunded_count: 1 (bool, optional) - return `refunded count`
```suggestion
	+ refunded_count: 1 (bool, optional) - Return `refunded count`
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ donation_amount: 1 (bool, optional) - return `donation amount`
```suggestion
	+ donation_amount: 1 (bool, optional) - Return `donation amount`
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ refunded_amount: 1 (bool, optional) - return `refunded amount`
```suggestion
	+ refunded_amount: 1 (bool, optional) - Return `refunded amount`
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +          "donation_amount": 2470,
```suggestion
          "donation_amount": 124670,
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ per_page: 5 (number, optional) - number of articles per page
```suggestion
	+ per_page: 5 (number, optional) - Number of articles per page
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +    + page: 1 (number, optional) - current page
```suggestion
    + page: 1 (number, optional) - Current page
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-game.apib
> +          "username": "Likyaz",
```suggestion
          "username": "lululombard",
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                          "provider_type": "Minecraft"
```suggestion
                          "provider_type": "Minecraft",
                          "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                      "type_provider": "Minecraft"
```suggestion
                      "previous_username": null,
                      "type_provider": "Minecraft",
                      "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                      "type_provider": "Discord"
```suggestion
                      "previous_username": null,
                      "type_provider": "Discord",
                      "uuid": 123456789012345678
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                        "provider_type": "Minecraft"
```suggestion
                        "provider_type": "Minecraft",
                        "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                          "provider_type": "Discord"
```suggestion
                          "provider_type": "Discord",
                          "uuid": 123456789012345678
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                        "provider_type": "Discord"
```suggestion
                        "provider_type": "Discord",
                        "uuid": 123456789012345678
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                "type_provider": "Minecraft"
```suggestion
                "previous_username": null,
                "type_provider": "Minecraft",
                "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                "type_provider": "Discord"
```suggestion
                "previous_username": null,
                "type_provider": "Discord",
                "uuid": 123456789012345678
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +                "displayName": "§4Likyaz"
```suggestion
                "display_name": "§4Likyaz"
```

2021-08-30 22:32 UTC, lululombard commented on doc/api-v1-public.apib
> +	+ online: 1 (bool, optional) - select only online player or all player
```suggestion
	+ online: 1 (bool, optional) - if set to 0 return all (including offline) players, otherwise return only online players
```

2021-08-30 23:30 UTC, Nano112 requested changes

2021-08-30 23:30 UTC, Nano112 commented on doc/api-v1-game.apib
> ++ Response 429
Add errors for already existing, invalid uuid's or badly formed

2021-08-30 23:30 UTC, Nano112 commented on doc/api-v1-game.apib
> +        "username": "lululombard",
remove username

2021-08-30 23:30 UTC, Nano112 commented on doc/api-v1-game.apib
> +    	"id": "player:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX",
remove id

2021-08-31 00:34 UTC, Nano112 requested changes

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +                  "id": 1,
bad id format
"player:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX"

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +# LAST DONATIONS [/api/v1/donation/last{?count}]
```suggestion
# LAST DONATION [/api/v1/donation/last{?count}]
```

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +### Last Donation [GET]
```suggestion
### List last Donation [GET]
```

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +# GRAPH DONATIONS [/api/v1/donation/stats/{delta_time}{?donation_count,refunded_count,donation_amount,refunded_amount}]
Maybe add start date and end date

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +# STATS DONATIONS [/api/v1/donation/graph{?count}]
Missing parameters

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +              "providers": [
username might be good

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +        "providers": [
username might be good

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +	+ player_id: 1 (number) - interne uuid
missing regex and support for multiple providers

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +### Get supported languages [GET]
might be good to add translation engine

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +# STATUS [/api/v1/server/status]
/api/v1/server/status -> /api/v1/network/minecraft/status 
tbd

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +# LIST PLAYER [/api/v1/server/player{?online}]
remove online parameter, waterfall allows only for players on the proxy

2021-08-31 00:34 UTC, Nano112 commented on doc/api-v1-public.apib
> +# SERVER MC PLAYER [/api/v1/server/player/count{?online}]
remove online parameter, waterfall allows only for players on the proxy

2021-09-03 20:14 UTC, merged