Add api v1
redcraft-org/redcraft_website_back pull request #6
Opened 2021-08-15 22:49 UTC by Likyaz

Api front v1 (api public) - Article: 

- Router: define a url pattern ".../api/v1/fr/article/{router_pattern}" and link to one function
- Serializer: get dict or object and return json
- ViewSet: get data from the database and process it with a serializer to return the information to the client

Route:
- List: http://127.0.0.1:8000/api/v1/fr/article/?category={category}
- Get article: http://127.0.0.1:8000/api/v1/fr/article/{id_article}/
- List last article: http://127.0.0.1:8000/api/v1/fr/article/last_article/?nb={nb}&category={category}

ps: Pagination of the route list will be done in a future commit.

2021-08-15 23:25 UTC, Cod3lta commented on api_v1/views/ArticleViewSet.py
> +    def __get_artile(self, language, article_id):
Typo

2021-08-15 23:25 UTC, Cod3lta commented on api_v1/serializer/ArticleSerializer.py
> +            'article': f'127.0.0.1:8000/api/v1/{obj["language"]}/article/{obj["id"]}/a-good-test'
Is it normal to have the address hardcoded?

2021-08-16 21:25 UTC, lululombard requested changes
Fix typo and all good

2021-08-16 21:41 UTC, lululombard approved these changes

2021-08-16 21:42 UTC, merged